version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - './db_data:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306

  wordpress:
    depends_on:
      - db
    image: wordpress:5.2.2-php7.1-apache
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    working_dir: /var/www/html
    volumes:
      - './wp-content:/var/www/html/wp-content'
      - './wp-themes:/var/www/html/wp-content/themes/'
      - './wp-plugins:/var/www/html/wp-content/plugins/'
      - './uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
volumes:
  db_data:
    driver: local